'use client'

import { useEffect } from 'react'

export function HowItWorksModal({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('keydown', handler)
    document.body.style.overflow = 'hidden'
    return () => {
      document.removeEventListener('keydown', handler)
      document.body.style.overflow = ''
    }
  }, [onClose])

  return (
    <div
      className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center"
      style={{ background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(4px)' }}
      onClick={onClose}
    >
      <div
        className="relative w-full sm:max-w-lg sm:mx-4 overflow-y-auto"
        style={{
          background: '#0f1117',
          border: '1px solid #1f2433',
          borderRadius: '20px 20px 0 0',
          maxHeight: '88vh',
          boxShadow: '0 -8px 40px rgba(0,0,0,0.5)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Pull handle — mobile only */}
        <div className="flex justify-center pt-3 pb-1 sm:hidden">
          <div style={{ width: 40, height: 4, borderRadius: 99, background: '#1f2433' }} />
        </div>

        {/* Header */}
        <div style={{
          position: 'sticky', top: 0, display: 'flex', alignItems: 'center',
          justifyContent: 'space-between', padding: '16px 20px',
          borderBottom: '1px solid #1f2433', background: '#0f1117', zIndex: 1,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              width: 28, height: 28, borderRadius: 8,
              background: 'linear-gradient(135deg, #818cf8 0%, #6366f1 100%)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '13px', fontWeight: '700', color: '#0f1117',
            }}>D</div>
            <span style={{ fontSize: 14, fontWeight: 600, color: '#f8fafc' }}>What is DataPulse?</span>
          </div>
          <button
            onClick={onClose}
            style={{
              width: 28, height: 28, borderRadius: '50%', border: 'none',
              background: 'transparent', cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: '#4b5675',
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Body */}
        <div style={{
          padding: '20px', paddingBottom: 32,
          display: 'flex', flexDirection: 'column', gap: '20px',
          fontSize: 14, color: '#94a3b8', lineHeight: 1.7,
        }}>

          {/* Hero line */}
          <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(129,140,248,0.08)', border: '1px solid rgba(129,140,248,0.2)' }}>
            <p style={{ margin: 0, fontSize: 15, fontWeight: 500, color: '#f8fafc' }}>
              DataPulse reads your spreadsheet and tells you what&apos;s in it — patterns, trends,
              key numbers, charts — all generated by AI in seconds.
            </p>
          </div>

          {/* The problem */}
          <div>
            <p style={{ margin: '0 0 10px', fontWeight: 600, color: '#f8fafc', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 18 }}>😩</span> The Problem
            </p>
            <p style={{ margin: 0 }}>
              You have a CSV or Excel file full of numbers. You know there&apos;s insight hiding in there,
              but building charts and writing analysis takes hours. You need a data analyst —
              but hiring one just for this is expensive and slow.
            </p>
          </div>

          {/* What it does */}
          <div>
            <p style={{ margin: '0 0 10px', fontWeight: 600, color: '#f8fafc', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 18 }}>✅</span> What DataPulse Does
            </p>
            <p style={{ margin: '0 0 12px' }}>
              You upload a file. The AI reads every row and gives you:
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                ['📊', 'Auto-generated charts', 'Bar, line, pie, doughnut — ready to screenshot'],
                ['🤖', 'AI narrative', 'A written summary of what your data actually means'],
                ['📈', 'Key metrics', 'The numbers that matter, with trend indicators'],
                ['🎯', 'Recommendations', 'Specific next steps based on patterns found'],
                ['💬', 'Q&A chat', 'Ask follow-up questions about your data, AI answers'],
                ['📄', 'Downloadable report', 'A full text report you can share with your team'],
              ].map(([icon, title, desc]) => (
                <div key={title as string} style={{ display: 'flex', gap: 10 }}>
                  <span style={{ fontSize: 16, flexShrink: 0 }}>{icon}</span>
                  <span><strong style={{ color: '#f8fafc' }}>{title}</strong> — {desc}</span>
                </div>
              ))}
            </div>
          </div>

          {/* How to test */}
          <div>
            <p style={{ margin: '0 0 10px', fontWeight: 600, color: '#f8fafc', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 18 }}>🚀</span> How to Try It Right Now
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {[
                ['1', 'Click <strong style="color:#f8fafc">✨ Try with sample data</strong> on the home page'],
                ['2', 'Wait 10–20 seconds while AI analyzes 200 rows of sales data'],
                ['3', 'See charts, key metrics, narrative, and recommendations'],
                ['4', 'Use the <strong style="color:#f8fafc">Q&A chat</strong> to ask follow-up questions'],
                ['5', 'Click <strong style="color:#f8fafc">Download Report</strong> if you want a shareable file'],
                ['6', 'Or upload your own CSV/Excel to see real results'],
              ].map(([num, step]) => (
                <div key={num as string} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  <span style={{
                    flexShrink: 0, width: 24, height: 24, borderRadius: '50%',
                    background: '#171923', border: '1px solid #1f2433',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 11, fontWeight: 700, color: '#818cf8',
                  }}>{num}</span>
                  <span dangerouslySetInnerHTML={{ __html: step as string }} />
                </div>
              ))}
            </div>
          </div>

          {/* Who it's for */}
          <div>
            <p style={{ margin: '0 0 10px', fontWeight: 600, color: '#f8fafc', display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 18 }}>👥</span> Who Is This For?
            </p>
            <p style={{ margin: 0 }}>
              Anyone sitting on data they haven&apos;t analyzed yet — marketing teams, small businesses,
              analysts, researchers, students. If you have a spreadsheet and need answers,
              DataPulse gives them in seconds.
            </p>
          </div>

          {/* Demo note */}
          <div style={{ padding: '12px 14px', borderRadius: 10, fontSize: 12, background: '#0d1017', border: '1px solid #1f2433' }}>
            <span style={{ color: '#818cf8', fontWeight: 600 }}>Demo limit:</span> You can run up to 5 analyses in this demo.
            Want unlimited access?{' '}
            <strong style={{ color: '#f8fafc' }}>Reach out to Abrar Tajwar Khan</strong> for a custom build.
          </div>
        </div>
      </div>
    </div>
  )
}
