import type { DpAnalysis } from './supabase'

export function generateReport(analysis: DpAnalysis): string {
  const date = new Date(analysis.created_at)
  const formattedDate = date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })

  const trendSymbol = (trend: string) => {
    if (trend === 'up') return '↑'
    if (trend === 'down') return '↓'
    return '→'
  }

  const separator  = '═'.repeat(50)
  const subSep     = '─'.repeat(50)

  let report = ''

  report += `DataPulse Analysis Report\n`
  report += `${separator}\n`
  report += `File:     ${analysis.filename}\n`
  report += `Analyzed: ${formattedDate}\n`
  report += `Rows:     ${analysis.row_count.toLocaleString()} | Columns: ${analysis.column_count}\n`
  report += `\n`

  // KEY METRICS
  report += `KEY METRICS\n`
  report += `${subSep}\n`
  if (analysis.key_metrics && analysis.key_metrics.length > 0) {
    for (const metric of analysis.key_metrics) {
      const symbol = trendSymbol(metric.trend)
      report += `${metric.label}: ${metric.value} ${symbol}\n`
      report += `  ${metric.significance}\n`
    }
  } else {
    report += `No metrics extracted.\n`
  }
  report += `\n`

  // ANALYSIS
  report += `ANALYSIS\n`
  report += `${subSep}\n`
  report += `${analysis.narrative ?? 'No analysis generated.'}\n`
  report += `\n`

  // RECOMMENDED ACTIONS
  report += `RECOMMENDED ACTIONS\n`
  report += `${subSep}\n`
  if (analysis.recommendations && analysis.recommendations.length > 0) {
    analysis.recommendations.forEach((rec, i) => {
      report += `${String(i + 1).padStart(2, '0')}. ${rec}\n`
    })
  } else {
    report += `No recommendations generated.\n`
  }
  report += `\n`

  // DATA OVERVIEW
  report += `DATA OVERVIEW\n`
  report += `${subSep}\n`
  report += `Columns: ${analysis.columns.join(', ')}\n`
  report += `\n`

  // Preview table
  if (analysis.data_preview && analysis.data_preview.length > 0) {
    report += `First ${analysis.data_preview.length} rows:\n`
    const headers = Object.keys(analysis.data_preview[0])
    const colWidths = headers.map((h) => {
      const maxVal = Math.max(
        h.length,
        ...analysis.data_preview.map((r) => String(r[h] ?? '').length)
      )
      return Math.min(maxVal, 20)
    })

    // Header row
    const headerRow = headers.map((h, i) => h.substring(0, colWidths[i]).padEnd(colWidths[i])).join(' | ')
    report += `${headerRow}\n`
    report += `${colWidths.map((w) => '-'.repeat(w)).join('-+-')}\n`

    // Data rows
    for (const row of analysis.data_preview) {
      const dataRow = headers
        .map((h, i) => String(row[h] ?? '').substring(0, colWidths[i]).padEnd(colWidths[i]))
        .join(' | ')
      report += `${dataRow}\n`
    }
  }

  report += `\n`
  report += `${subSep}\n`
  report += `Generated by DataPulse AI\n`
  report += `https://github.com/abrartajwar/datapulse-ai\n`

  return report
}

export function getReportFilename(analysis: DpAnalysis): string {
  const date = new Date(analysis.created_at)
  const dateStr = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
  const safeName = analysis.filename.replace(/\.[^.]+$/, '').replace(/[^a-z0-9]/gi, '-').toLowerCase()
  return `datapulse-${safeName}-${dateStr}.txt`
}
